name: grademate # Ensure this matches your project's actual name
description: A new Flutter project for login and password recovery.
publish_to: 'none' # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure compatibility with newer Dart SDK

dependencies:
  flutter:
    sdk: flutter

  # State management and routing
  provider: ^6.1.5+1    # Latest stable version
  go_router: ^16.2.1

  # Firebase packages
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1

  # File handling
  file_picker: ^10.3.3
  intl: ^0.20.2
  path_provider: ^2.1.2
  share_plus: ^12.0.0
  dio: ^5.4.1
  webview_flutter: ^4.13.0

  syncfusion_flutter_pdfviewer: ^31.1.19
  video_player: ^2.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  email_validator: ^3.0.0
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  http: ^1.5.0
  flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Latest stable version
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
