// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBME32z0wLGUaWinlyIB5TwwhHytYdxNPU',
    appId: '1:106171512173:web:c18aa84b8ee9d440ac9664',
    messagingSenderId: '106171512173',
    projectId: 'grademate-app',
    authDomain: 'grademate-app.firebaseapp.com',
    storageBucket: 'grademate-app.firebasestorage.app',
    measurementId: 'G-E04P14V5QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoQ7woIsDMaRyFfyWW6eBGmDj2u39nF28',
    appId: '1:106171512173:android:7ecc6159f31faa1fac9664',
    messagingSenderId: '106171512173',
    projectId: 'grademate-app',
    storageBucket: 'grademate-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVGCoWQteFt87J3tG_hz4sq4CCwu1-Kc8',
    appId: '1:106171512173:ios:313e07bf213b355bac9664',
    messagingSenderId: '106171512173',
    projectId: 'grademate-app',
    storageBucket: 'grademate-app.firebasestorage.app',
    iosBundleId: 'com.example.grademate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVGCoWQteFt87J3tG_hz4sq4CCwu1-Kc8',
    appId: '1:106171512173:ios:313e07bf213b355bac9664',
    messagingSenderId: '106171512173',
    projectId: 'grademate-app',
    storageBucket: 'grademate-app.firebasestorage.app',
    iosBundleId: 'com.example.grademate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBME32z0wLGUaWinlyIB5TwwhHytYdxNPU',
    appId: '1:106171512173:web:927f7d2309d32df3ac9664',
    messagingSenderId: '106171512173',
    projectId: 'grademate-app',
    authDomain: 'grademate-app.firebaseapp.com',
    storageBucket: 'grademate-app.firebasestorage.app',
    measurementId: 'G-MZPZDN6BDE',
  );
}
